spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zboynabc.mysql.database.azure.com:3306/smartcar
    username: zboyn
    password: faith213.5

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neu.zboyn.car.model
  configuration:
    # 驼峰和下划线命名自动转换
    map-underscore-to-camel-case: true

file:
  upload-dir: "C:/Users/27978/Desktop/SmartCar/upload"
  server-url: http://localhost:8080

server:
  port: 8080

ai:
  detection-service:
    url: "http://127.0.0.1:8001/detect"